server:
  port: 8088

spring:
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true
  application:
    name: DatingApp
  main:
    allow-bean-definition-overriding: true
  #Email:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kientrungak@gmail.com
    password: hrjp psbp oqce agsq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #multipart
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    #url: jdbc:mysql://datingapp-1.cjgk64oswovm.ap-southeast-2.rds.amazonaws.com:3306/datingapp
    #username: root
    #password: huongntn04
    url: jdbc:mysql://localhost:3306/datingapp
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

firebase:
  storage:
    bucket: gs://datingapp-f4ecb.appspot.com

#########
jwt:
  #secret: kien_key
  expiration: 3600

cloud:
  storage:
    bucket-name: gs://datingapp-f4ecb.appspot.com

#payment
payment:
  vnPay:
    payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: 27APOTHS
    secretKey: 002W55MOJX8C5BLTEIDQ15JWXWRSYW11
    returnUrl: http://localhost:8080/api/v1/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other
